// Builds static/admin/decap-cms.js: the pinned Decap CMS bundle with slate-react's Android IME fix backported.
//
// On Android, Decap's rich text editor (Slate) cancels the keyboard's Hangul composition when typing starts on an empty
// line, so the first letter is left as separate jamo (ㅇ안녕 instead of 안녕). slate-react fixed this in 0.126.3
// (https://github.com/ianstormtaylor/slate/pull/6096), but Decap bundles slate-react 0.117, and slate-react 0.126 needs
// newer slate core packages than Decap uses. So this script applies that PR to Decap's minified bundle. Each patch
// names the upstream change it mirrors, and the script stops if any original code is not found exactly once, e.g.
// after a Decap upgrade: re-map the patches against the new bundle (or drop them once Decap ships slate-react 0.126.3+).
//
// Usage: node scripts/patch-decap.mjs
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

export const DECAP_VERSION = '3.15.1';
const SOURCE_URL = `https://unpkg.com/decap-cms@${DECAP_VERSION}/dist/decap-cms.js`;
const SOURCE_SHA256 = '952395b66c20e29ee3989e2924de6a5e31e2e2c0ec8daa1c5fa7cf79286b1e06';
const OUTPUT = new URL('../static/admin/decap-cms.js', import.meta.url);
const LICENSE_OUTPUT = new URL('../static/admin/decap-cms.js.LICENSE.txt', import.meta.url);

export const HEADER = `/*! decap-cms ${DECAP_VERSION} with the slate-react Android IME fix (ianstormtaylor/slate#6096) backported.`
  + ' Generated by scripts/patch-decap.mjs; do not edit. */\n';

// Minified names in slate-react's module of this bundle: t = editor, i = flushing, o = composition end timer,
// a = flush timer, d = flush, p = updatePlaceholderVisibility, JQ = EDITOR_TO_PENDING_DIFFS,
// eJ = EDITOR_TO_PENDING_SELECTION, VQ = IS_COMPOSING, vQ = IS_ANDROID, IQ = IS_NODE_MAP_DIRTY,
// tJ = EDITOR_TO_FORCE_RENDER, sK = Node, _Z = ReactEditor, wZ = useSlateStatic, te = react-dom.
const leafIsEmpty = 'e=>{try{return 0===sK.leaf(t,e.path).text.length}catch(e){return!1}}';

export const PATCHES = [
  {
    name: 'ZeroWidthString renders the zero-width text node on Android too (string.tsx)',
    find: 'vQ&&n?null:"\\ufeff",n?o.createElement("br",null):null)',
    replace: '"\\ufeff",n?o.createElement("br",null):null)',
  },
  {
    name: 'TextString leaves the span alone while the IME composes in it (string.tsx)',
    find: 'RZ=e=>{var{text:t,isTrailing:n=!1}=e,r=(0,o.useRef)(null),i=()=>"".concat(null!=t?t:"").concat(n?"\\n":""),'
      + '[a]=(0,o.useState)(i);return CZ(()=>{var e=i();r.current&&r.current.textContent!==e&&(r.current.textContent=e)})',
    replace: 'RZ=e=>{var{text:t,isTrailing:n=!1}=e,s=wZ(),r=(0,o.useRef)(null),i=()=>"".concat(null!=t?t:"").concat(n?"\\n":""),'
      + '[a]=(0,o.useState)(i);return CZ(()=>{var e=i();if(r.current&&r.current.textContent!==e){'
      + 'if(vQ&&VQ.get(s)){var l=_Z.getWindow(s).getSelection(),c=l&&l.anchorNode;if(c&&r.current.contains(c))return}'
      + 'r.current.textContent=e}})',
  },
  {
    name: 'Android input manager state: isCompositionLive, hasPendingDiffsInEmptyLeaf, composition input tracking',
    find: '{var{editor:t,scheduleOnDOMSelectionChange:n,onDOMSelectionChange:r}=e,i=!1,o=null,a=null,s=null,l=0,u=!1,c=()=>{',
    replace: '{var{editor:t,scheduleOnDOMSelectionChange:n,onDOMSelectionChange:r}=e,i=!1,o=null,a=null,s=null,l=0,u=!1,'
      + 'imeActivityAt=0,imeCleared=!1,'
      + 'imeLive=()=>{if(!VQ.get(t)||imeCleared)return!1;try{var e=_Z.toDOMNode(t,t),n=_Z.getWindow(t).document.activeElement;'
      + 'if(n!==e&&!e.contains(n))return!1}catch(e){}return Date.now()-imeActivityAt<5e3},'
      + `imeEmptyLeaf=()=>{var e=JQ.get(t);return!!e&&e.some(${leafIsEmpty})},`
      + 'imeInput=e=>{var n=e.inputType;if("insertCompositionText"===n||"deleteCompositionText"===n)'
      + 'if(imeActivityAt=Date.now(),e.data)imeCleared=!1;'
      + `else{imeCleared=!0;var r=JQ.get(t);r&&r.length&&r.every(${leafIsEmpty})&&(JQ.set(t,[]),eJ.delete(t))}},`
      + 'c=()=>{',
  },
  {
    name: 'flush waits while the IME composes into an empty leaf',
    find: 'd=()=>{if(a&&(clearTimeout(a),a=null),s&&(clearTimeout(s),s=null),m()||g()){',
    replace: 'd=()=>{if(a&&(clearTimeout(a),a=null),s&&(clearTimeout(s),s=null),imeLive()&&imeEmptyLeaf())'
      + 'return void(a=setTimeout(d,50));if(m()||g()){',
  },
  {
    name: 'compositionend applies the held diffs synchronously; compositionstart resets the tracking',
    find: 'handleCompositionEnd:e=>{o&&clearTimeout(o),o=setTimeout(()=>{VQ.set(t,!1),d()},25)},'
      + 'handleCompositionStart:e=>{VQ.set(t,!0),o&&(clearTimeout(o),o=null)}',
    replace: 'handleCompositionEnd:e=>{if(o&&clearTimeout(o),imeEmptyLeaf()&&!i)return te.flushSync(()=>{VQ.set(t,!1),d()}),void p();'
      + 'o=setTimeout(()=>{var e;VQ.set(t,!1),d(),imeCleared&&(null===(e=tJ.get(t))||void 0===e||e()),p()},25)},'
      + 'handleCompositionStart:e=>{VQ.set(t,!0),imeActivityAt=Date.now(),imeCleared=!1,o&&(clearTimeout(o),o=null)}',
  },
  {
    name: 'beforeinput tracks composition activity and drops held diffs of a cancelled composition',
    find: 'handleDOMBeforeInput:e=>{var n;if(a&&(clearTimeout(a),a=null),!IQ.get(t)){var{inputType:r}=e,',
    replace: 'handleDOMBeforeInput:e=>{var n;if(a&&(clearTimeout(a),a=null),!IQ.get(t)){imeInput(e);var{inputType:r}=e,',
  },
  {
    name: 'no source map: it would describe the unpatched code',
    find: '\n//# sourceMappingURL=decap-cms.js.map',
    replace: '\n',
  },
];

export function patchDecap(source) {
  if (/\bime(ActivityAt|Cleared|Live|EmptyLeaf|Input)\b/u.test(source)) throw new Error('The bundle already uses the names the patches add.');
  return HEADER + PATCHES.reduce((code, { name, find, replace }) => {
    const count = code.split(find).length - 1;
    if (count !== 1) throw new Error(`${name}: expected the original code once, found it ${count} times.`);
    return code.replace(find, () => replace);
  }, source);
}

async function download(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.text();
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const source = await download(SOURCE_URL);
  const hash = createHash('sha256').update(source).digest('hex');
  if (hash !== SOURCE_SHA256) throw new Error(`${SOURCE_URL} changed: sha256 ${hash}`);
  await writeFile(OUTPUT, patchDecap(source));
  await writeFile(LICENSE_OUTPUT, await download(`${SOURCE_URL}.LICENSE.txt`));
  console.log(`Wrote ${OUTPUT.pathname} (${PATCHES.length} patches) and its license file.`);
}
